remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Studijní opora kurzů kyberbezpečnosti Czechitas"
description: "Podklady pro samostudium a další zajímavé materiály sdílené na kurzech kyberbezpečnosti"
google_analytics: "G-04GZEJ8ZX4"
